apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-creator
  namespace: default
subjects:
- kind: ServiceAccount
  name: andy-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: pvc-creator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-creator
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: andy-serviceaccount
  namespace: default
